# Generated by Django 5.2.1 on 2025-05-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('com_port', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('model_number', models.CharField(max_length=50)),
                ('max_capacity', models.DecimalField(decimal_places=2, help_text='Maximum weight capacity in kg', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_connection_status', models.CharField(default='disconnected', max_length=50)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
