# Generated by Django 5.2.1 on 2025-05-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0002_product_weighingprocess_weighingrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='erp_product_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
