# Generated by Django 5.2.1 on 2025-05-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0004_deliverynote_weighingrecord_delivery_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingrecord',
            name='barcode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
