# Generated by Django 5.2.1 on 2025-05-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0006_erpsystem_companysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='weighingprocess',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
