# Generated by Django 5.2.1 on 2025-05-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0007_alter_product_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='erp_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='erp_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='api_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
