# Generated by Django 5.2.1 on 2025-05-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0008_companysettings_erp_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingprocess',
            name='allow_manual_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weighingprocess',
            name='max_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='weighingprocess',
            name='min_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='weighingprocess',
            name='weight_rounding',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
