# Generated by Django 5.2.1 on 2025-05-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0009_weighingprocess_allow_manual_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='database_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weighingprocess',
            name='weight_rounding',
            field=models.IntegerField(blank=True, choices=[(3, '0.001'), (2, '0.01'), (1, '0.1'), (0, '1.0')], default=2, null=True),
        ),
    ]
