# Generated by Django 5.2.1 on 2025-07-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0010_companysettings_database_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='com_port',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
