# Generated by Django 5.2.1 on 2025-08-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0012_alter_scale_max_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='scale',
            name='baud_rate',
            field=models.IntegerField(default=9600),
        ),
        migrations.AddField(
            model_name='scale',
            name='data_bits',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='scale',
            name='parity',
            field=models.CharField(choices=[('N', 'None'), ('E', 'Even'), ('O', 'Odd')], default='N', max_length=10),
        ),
        migrations.AddField(
            model_name='scale',
            name='stop_bits',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scale',
            name='timeout',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='scale',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scale',
            name='model_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
