# Generated by Django 5.2.1 on 2025-08-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0012_alter_scale_max_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingprocess',
            name='tare_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
