# Generated by Django 5.2.1 on 2025-08-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0013_weighingprocess_tare_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighingprocess',
            name='tare_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
