# Generated by Django 5.2.1 on 2025-08-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0015_alter_deliverynote_status_alter_driver_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingprocess',
            name='process_type',
            field=models.CharField(blank=True, choices=[('WeighBridge', 'WeighBridge'), ('Manual', 'Manual'), ('Automated', 'Automated')], default='WeighBridge', max_length=100, null=True),
        ),
    ]
