# Generated by Django 5.2.1 on 2025-08-05 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0016_weighingprocess_process_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scale.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='tare_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='scale',
            name='tare_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
