# Generated by Django 5.2.1 on 2025-08-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0017_deliverynote_product_product_tare_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='last_connection_status',
            field=models.CharField(blank=True, default='disconnected', max_length=50, null=True),
        ),
    ]
