# Generated by Django 5.2.1 on 2025-09-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0018_alter_scale_last_connection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='odoo_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='odoo_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='partner_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
