# Generated by Django 5.2.1 on 2025-09-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0019_deliverynote_odoo_data_deliverynote_odoo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='partner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
