# Generated by Django 5.2.1 on 2025-09-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0020_alter_deliverynote_partner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='is_being_scanned',
            field=models.BooleanField(default=False, help_text='True when this delivery note is currently active in ctl_workflow'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='scanned_bales_count',
            field=models.IntegerField(default=0, help_text='Number of bales scanned for this delivery note'),
        ),
        migrations.AlterField(
            model_name='weighingprocess',
            name='process_type',
            field=models.CharField(blank=True, choices=[('WeighBridge', 'WeighBridge'), ('Manual', 'Manual'), ('Automated', 'Automated'), ('ctl_workflow', 'CTL Workflow')], default='WeighBridge', max_length=100, null=True),
        ),
    ]
