# Generated by Django 5.2.1 on 2025-09-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0021_deliverynote_is_being_scanned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='scanned_barcodes',
            field=models.JSONField(blank=True, default=list, help_text='List of barcodes that have been scanned for this delivery note'),
        ),
    ]
